# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reac_no_iso_no_adi.ui'
#
# Created: Sat Jan 14 21:07:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ventana_dis_no_iso_no_adi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(788, 628)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 50, 431, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot = PlotWidget(self.layoutWidget)
        self.plot.setObjectName("plot")
        self.verticalLayout_2.addWidget(self.plot)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lb_cao_10 = QtGui.QLabel(self.layoutWidget)
        self.lb_cao_10.setObjectName("lb_cao_10")
        self.horizontalLayout_11.addWidget(self.lb_cao_10)
        self.le_xa = QtGui.QLineEdit(self.layoutWidget)
        self.le_xa.setObjectName("le_xa")
        self.horizontalLayout_11.addWidget(self.le_xa)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.lb_cao_2 = QtGui.QLabel(self.layoutWidget)
        self.lb_cao_2.setObjectName("lb_cao_2")
        self.horizontalLayout_12.addWidget(self.lb_cao_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.le_time = QtGui.QLineEdit(self.layoutWidget)
        self.le_time.setObjectName("le_time")
        self.horizontalLayout_3.addWidget(self.le_time)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.lb_cao_16 = QtGui.QLabel(self.layoutWidget)
        self.lb_cao_16.setObjectName("lb_cao_16")
        self.horizontalLayout_17.addWidget(self.lb_cao_16)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.le_temp_b = QtGui.QLineEdit(self.layoutWidget)
        self.le_temp_b.setObjectName("le_temp_b")
        self.horizontalLayout_19.addWidget(self.le_temp_b)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_19)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.btn_mostrar_resultado = QtGui.QPushButton(self.layoutWidget)
        self.btn_mostrar_resultado.setObjectName("btn_mostrar_resultado")
        self.verticalLayout_2.addWidget(self.btn_mostrar_resultado)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 20, 341, 611))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_cao_6 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_6.setObjectName("lb_cao_6")
        self.horizontalLayout_7.addWidget(self.lb_cao_6)
        self.cb_orden = QtGui.QComboBox(self.groupBox_2)
        self.cb_orden.setObjectName("cb_orden")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.horizontalLayout_7.addWidget(self.cb_orden)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lb_cao_9 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_9.setObjectName("lb_cao_9")
        self.horizontalLayout_10.addWidget(self.lb_cao_9)
        self.le_temp_ini = QtGui.QLineEdit(self.groupBox_2)
        self.le_temp_ini.setObjectName("le_temp_ini")
        self.horizontalLayout_10.addWidget(self.le_temp_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_cao_5 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_5.setObjectName("lb_cao_5")
        self.horizontalLayout_6.addWidget(self.lb_cao_5)
        self.le_concentracion_ini = QtGui.QLineEdit(self.groupBox_2)
        self.le_concentracion_ini.setObjectName("le_concentracion_ini")
        self.horizontalLayout_6.addWidget(self.le_concentracion_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_cao_4 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_4.setObjectName("lb_cao_4")
        self.horizontalLayout_5.addWidget(self.lb_cao_4)
        self.le_ener_act = QtGui.QLineEdit(self.groupBox_2)
        self.le_ener_act.setObjectName("le_ener_act")
        self.horizontalLayout_5.addWidget(self.le_ener_act)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lb_cao_7 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_7.setObjectName("lb_cao_7")
        self.horizontalLayout_8.addWidget(self.lb_cao_7)
        self.le_k = QtGui.QLineEdit(self.groupBox_2)
        self.le_k.setObjectName("le_k")
        self.horizontalLayout_8.addWidget(self.le_k)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lb_cao_8 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_8.setObjectName("lb_cao_8")
        self.horizontalLayout_9.addWidget(self.lb_cao_8)
        self.le_calor_reaccion = QtGui.QLineEdit(self.groupBox_2)
        self.le_calor_reaccion.setObjectName("le_calor_reaccion")
        self.horizontalLayout_9.addWidget(self.le_calor_reaccion)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lb_cao_11 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_11.setObjectName("lb_cao_11")
        self.horizontalLayout_13.addWidget(self.lb_cao_11)
        self.le_peso_molecular = QtGui.QLineEdit(self.groupBox_2)
        self.le_peso_molecular.setObjectName("le_peso_molecular")
        self.horizontalLayout_13.addWidget(self.le_peso_molecular)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lb_cao_12 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_12.setObjectName("lb_cao_12")
        self.horizontalLayout_14.addWidget(self.lb_cao_12)
        self.le_calor_especifico = QtGui.QLineEdit(self.groupBox_2)
        self.le_calor_especifico.setObjectName("le_calor_especifico")
        self.horizontalLayout_14.addWidget(self.le_calor_especifico)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lb_cao_13 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_13.setObjectName("lb_cao_13")
        self.horizontalLayout_15.addWidget(self.lb_cao_13)
        self.le_densidad = QtGui.QLineEdit(self.groupBox_2)
        self.le_densidad.setObjectName("le_densidad")
        self.horizontalLayout_15.addWidget(self.le_densidad)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lb_cao_14 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_14.setObjectName("lb_cao_14")
        self.horizontalLayout_16.addWidget(self.lb_cao_14)
        self.le_coef_transmision = QtGui.QLineEdit(self.groupBox_2)
        self.le_coef_transmision.setObjectName("le_coef_transmision")
        self.horizontalLayout_16.addWidget(self.le_coef_transmision)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.lb_cao_27 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_27.setObjectName("lb_cao_27")
        self.horizontalLayout_29.addWidget(self.lb_cao_27)
        self.le_area = QtGui.QLineEdit(self.groupBox_2)
        self.le_area.setObjectName("le_area")
        self.horizontalLayout_29.addWidget(self.le_area)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.lb_cao_28 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_28.setObjectName("lb_cao_28")
        self.horizontalLayout_30.addWidget(self.lb_cao_28)
        self.le_volumen = QtGui.QLineEdit(self.groupBox_2)
        self.le_volumen.setObjectName("le_volumen")
        self.horizontalLayout_30.addWidget(self.le_volumen)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.lb_cao_43 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_43.setObjectName("lb_cao_43")
        self.horizontalLayout_45.addWidget(self.lb_cao_43)
        self.le_temp_int = QtGui.QLineEdit(self.groupBox_2)
        self.le_temp_int.setObjectName("le_temp_int")
        self.horizontalLayout_45.addWidget(self.le_temp_int)
        self.verticalLayout.addLayout(self.horizontalLayout_45)
        self.groupBox = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rb_exo = QtGui.QRadioButton(self.groupBox)
        self.rb_exo.setChecked(True)
        self.rb_exo.setObjectName("rb_exo")
        self.verticalLayout_3.addWidget(self.rb_exo)
        self.rb_endo = QtGui.QRadioButton(self.groupBox)
        self.rb_endo.setObjectName("rb_endo")
        self.verticalLayout_3.addWidget(self.rb_endo)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(390, 520, 315, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_cao = QtGui.QLabel(self.layoutWidget1)
        self.lb_cao.setObjectName("lb_cao")
        self.horizontalLayout_2.addWidget(self.lb_cao)
        self.le_conv_fin = QtGui.QLineEdit(self.layoutWidget1)
        self.le_conv_fin.setObjectName("le_conv_fin")
        self.horizontalLayout_2.addWidget(self.le_conv_fin)
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(390, 486, 315, 29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_cao_3 = QtGui.QLabel(self.layoutWidget2)
        self.lb_cao_3.setObjectName("lb_cao_3")
        self.horizontalLayout_4.addWidget(self.lb_cao_3)
        self.le_conv_ini = QtGui.QLineEdit(self.layoutWidget2)
        self.le_conv_ini.setObjectName("le_conv_ini")
        self.horizontalLayout_4.addWidget(self.le_conv_ini)
        self.btn_calcular = QtGui.QPushButton(Form)
        self.btn_calcular.setGeometry(QtCore.QRect(390, 560, 315, 27))
        self.btn_calcular.setObjectName("btn_calcular")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "DIRe", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_10.setText(QtGui.QApplication.translate("Form", "Xa", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_2.setText(QtGui.QApplication.translate("Form", "Tiempo [min]", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_16.setText(QtGui.QApplication.translate("Form", "Temp [k]", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mostrar_resultado.setText(QtGui.QApplication.translate("Form", "Mostrar resultado", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Parámetros", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_6.setText(QtGui.QApplication.translate("Form", "Orden Reacción", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(0, QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(1, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(2, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_9.setText(QtGui.QApplication.translate("Form", "Temperatura inicial [K]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_temp_ini.setText(QtGui.QApplication.translate("Form", "298", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_5.setText(QtGui.QApplication.translate("Form", "Concentración inicial [mol/l]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_concentracion_ini.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_4.setText(QtGui.QApplication.translate("Form", "Energía de activación [J/mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_ener_act.setText(QtGui.QApplication.translate("Form", "62325", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_7.setText(QtGui.QApplication.translate("Form", "Constante ko [(l/mol)^(n-1)/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_k.setText(QtGui.QApplication.translate("Form", "4e6", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_8.setText(QtGui.QApplication.translate("Form", "Calor de reacción [J/mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_calor_reaccion.setText(QtGui.QApplication.translate("Form", "167000", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_11.setText(QtGui.QApplication.translate("Form", "Peso molecular [g/mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_peso_molecular.setText(QtGui.QApplication.translate("Form", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_12.setText(QtGui.QApplication.translate("Form", "Calor específico [J/mol·K]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_calor_especifico.setText(QtGui.QApplication.translate("Form", "172307.69", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_13.setText(QtGui.QApplication.translate("Form", "Densidad de la mezcla [g/l]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_densidad.setText(QtGui.QApplication.translate("Form", "1.95", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_14.setText(QtGui.QApplication.translate("Form", "Coef transmision calor [W/m^2·K]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_coef_transmision.setText(QtGui.QApplication.translate("Form", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_27.setText(QtGui.QApplication.translate("Form", "Area de transmision de calor [m^2]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_area.setText(QtGui.QApplication.translate("Form", "3.3", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_28.setText(QtGui.QApplication.translate("Form", "Volumen [l]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_volumen.setText(QtGui.QApplication.translate("Form", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_43.setText(QtGui.QApplication.translate("Form", "Temperatura del intercambiador [K]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_temp_int.setText(QtGui.QApplication.translate("Form", "393", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Tipo de reacción", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_exo.setText(QtGui.QApplication.translate("Form", "Exotérmico", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_endo.setText(QtGui.QApplication.translate("Form", "Endotérmico", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao.setText(QtGui.QApplication.translate("Form", "Conversión final", None, QtGui.QApplication.UnicodeUTF8))
        self.le_conv_fin.setText(QtGui.QApplication.translate("Form", "0.7", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_3.setText(QtGui.QApplication.translate("Form", "Conversión inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.le_conv_ini.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_calcular.setText(QtGui.QApplication.translate("Form", "Calcular", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
