# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'condiciones_optimas.ui'
#
# Created: Tue Dec 27 20:36:24 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Optimizacion(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(788, 452)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(420, 110, 341, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_conv_optima = QtGui.QLineEdit(self.layoutWidget)
        self.le_conv_optima.setObjectName("le_conv_optima")
        self.horizontalLayout.addWidget(self.le_conv_optima)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_tiempo_optimo = QtGui.QLineEdit(self.layoutWidget)
        self.le_tiempo_optimo.setObjectName("le_tiempo_optimo")
        self.horizontalLayout_2.addWidget(self.le_tiempo_optimo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.btn_calcular = QtGui.QPushButton(self.layoutWidget)
        self.btn_calcular.setObjectName("btn_calcular")
        self.verticalLayout_2.addWidget(self.btn_calcular)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 20, 421, 411))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_cao_6 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_6.setObjectName("lb_cao_6")
        self.horizontalLayout_7.addWidget(self.lb_cao_6)
        self.cb_orden = QtGui.QComboBox(self.groupBox_2)
        self.cb_orden.setObjectName("cb_orden")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.horizontalLayout_7.addWidget(self.cb_orden)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lb_cao_15 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_15.setObjectName("lb_cao_15")
        self.horizontalLayout_17.addWidget(self.lb_cao_15)
        self.le_a = QtGui.QLineEdit(self.groupBox_2)
        self.le_a.setObjectName("le_a")
        self.horizontalLayout_17.addWidget(self.le_a)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lb_cao_9 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_9.setObjectName("lb_cao_9")
        self.horizontalLayout_10.addWidget(self.lb_cao_9)
        self.le_temp_ini = QtGui.QLineEdit(self.groupBox_2)
        self.le_temp_ini.setObjectName("le_temp_ini")
        self.horizontalLayout_10.addWidget(self.le_temp_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_cao_5 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_5.setObjectName("lb_cao_5")
        self.horizontalLayout_6.addWidget(self.lb_cao_5)
        self.le_concentracion_ini = QtGui.QLineEdit(self.groupBox_2)
        self.le_concentracion_ini.setObjectName("le_concentracion_ini")
        self.horizontalLayout_6.addWidget(self.le_concentracion_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_cao_4 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_4.setObjectName("lb_cao_4")
        self.horizontalLayout_5.addWidget(self.lb_cao_4)
        self.le_ener_act = QtGui.QLineEdit(self.groupBox_2)
        self.le_ener_act.setObjectName("le_ener_act")
        self.horizontalLayout_5.addWidget(self.le_ener_act)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lb_cao_7 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_7.setObjectName("lb_cao_7")
        self.horizontalLayout_8.addWidget(self.lb_cao_7)
        self.le_k = QtGui.QLineEdit(self.groupBox_2)
        self.le_k.setObjectName("le_k")
        self.horizontalLayout_8.addWidget(self.le_k)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.lb_cao_28 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_28.setObjectName("lb_cao_28")
        self.horizontalLayout_30.addWidget(self.lb_cao_28)
        self.le_volumen = QtGui.QLineEdit(self.groupBox_2)
        self.le_volumen.setObjectName("le_volumen")
        self.horizontalLayout_30.addWidget(self.le_volumen)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.lb_cao_27 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_27.setObjectName("lb_cao_27")
        self.horizontalLayout_29.addWidget(self.lb_cao_27)
        self.le_coste_reac = QtGui.QLineEdit(self.groupBox_2)
        self.le_coste_reac.setObjectName("le_coste_reac")
        self.horizontalLayout_29.addWidget(self.le_coste_reac)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.lb_cao_43 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_43.setObjectName("lb_cao_43")
        self.horizontalLayout_45.addWidget(self.lb_cao_43)
        self.le_aumento_valor = QtGui.QLineEdit(self.groupBox_2)
        self.le_aumento_valor.setObjectName("le_aumento_valor")
        self.horizontalLayout_45.addWidget(self.le_aumento_valor)
        self.verticalLayout.addLayout(self.horizontalLayout_45)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Conversión  optima (%): ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Tiempo óptimo de operación (s): ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_calcular.setText(QtGui.QApplication.translate("Form", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Parámetros", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_6.setText(QtGui.QApplication.translate("Form", "Orden Reacción", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(0, QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(1, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(2, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_15.setText(QtGui.QApplication.translate("Form", "a [mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_a.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_9.setText(QtGui.QApplication.translate("Form", "Temperatura inicial [K]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_temp_ini.setText(QtGui.QApplication.translate("Form", "400", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_5.setText(QtGui.QApplication.translate("Form", "Concentración inicial [mol/l]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_concentracion_ini.setText(QtGui.QApplication.translate("Form", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_4.setText(QtGui.QApplication.translate("Form", "Energía de activación [J/mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_ener_act.setText(QtGui.QApplication.translate("Form", "50000", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_7.setText(QtGui.QApplication.translate("Form", "Constante ko", None, QtGui.QApplication.UnicodeUTF8))
        self.le_k.setText(QtGui.QApplication.translate("Form", "4e6", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_28.setText(QtGui.QApplication.translate("Form", "Volumen [l]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_volumen.setText(QtGui.QApplication.translate("Form", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_27.setText(QtGui.QApplication.translate("Form", "Coste de reacción [€/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_coste_reac.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_43.setText(QtGui.QApplication.translate("Form", "Valor aumentado por mol transformado [€]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_aumento_valor.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))

