# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created: Sun Jan 22 13:23:34 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ventana_principal(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 425)
        Form.setMinimumSize(QtCore.QSize(570, 425))
        Form.setMaximumSize(QtCore.QSize(570, 425))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(10, 11, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_titulo = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setWeight(75)
        font.setBold(True)
        self.lb_titulo.setFont(font)
        self.lb_titulo.setTextFormat(QtCore.Qt.PlainText)
        self.lb_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_titulo.setWordWrap(True)
        self.lb_titulo.setObjectName("lb_titulo")
        self.verticalLayout_2.addWidget(self.lb_titulo)
        spacerItem1 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.lb_titulo_2 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.lb_titulo_2.setFont(font)
        self.lb_titulo_2.setTextFormat(QtCore.Qt.PlainText)
        self.lb_titulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_titulo_2.setWordWrap(True)
        self.lb_titulo_2.setObjectName("lb_titulo_2")
        self.verticalLayout_2.addWidget(self.lb_titulo_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lb_foto_1 = QtGui.QLabel(Form)
        self.lb_foto_1.setMinimumSize(QtCore.QSize(250, 151))
        self.lb_foto_1.setMaximumSize(QtCore.QSize(250, 151))
        self.lb_foto_1.setObjectName("lb_foto_1")
        self.horizontalLayout.addWidget(self.lb_foto_1)
        self.lb_foto_2 = QtGui.QLabel(Form)
        self.lb_foto_2.setMinimumSize(QtCore.QSize(250, 151))
        self.lb_foto_2.setMaximumSize(QtCore.QSize(250, 151))
        self.lb_foto_2.setObjectName("lb_foto_2")
        self.horizontalLayout.addWidget(self.lb_foto_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.btn_empezar = QtGui.QPushButton(Form)
        self.btn_empezar.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_empezar.setFont(font)
        self.btn_empezar.setObjectName("btn_empezar")
        self.horizontalLayout_2.addWidget(self.btn_empezar)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.btn_salir = QtGui.QPushButton(Form)
        self.btn_salir.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_salir.setFont(font)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_2.addWidget(self.btn_salir)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.mostrar_guia = QtGui.QPushButton(Form)
        self.mostrar_guia.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mostrar_guia.setFont(font)
        self.mostrar_guia.setObjectName("mostrar_guia")
        self.horizontalLayout_2.addWidget(self.mostrar_guia)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem10 = QtGui.QSpacerItem(20, 11, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "DIRe", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_titulo.setText(QtGui.QApplication.translate("Form", "DISEÑO DE REACTORES IDEALES", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_titulo_2.setText(QtGui.QApplication.translate("Form", "Diseño de Procesos Químicos - Curso 2016/2017", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_foto_1.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_foto_2.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_empezar.setText(QtGui.QApplication.translate("Form", "Empezar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_salir.setText(QtGui.QApplication.translate("Form", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.mostrar_guia.setText(QtGui.QApplication.translate("Form", "Guia Usuario", None, QtGui.QApplication.UnicodeUTF8))

