# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_FP_general.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1020, 659)
        self._2 = QtGui.QHBoxLayout(Form)
        self._2.setContentsMargins(-1, 20, -1, 25)
        self._2.setObjectName(_fromUtf8("_2"))
        spacerItem = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.Izquierda = QtGui.QVBoxLayout()
        self.Izquierda.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Izquierda.setContentsMargins(0, -1, -1, -1)
        self.Izquierda.setObjectName(_fromUtf8("Izquierda"))
        self.Reaccion = QtGui.QGroupBox(Form)
        self.Reaccion.setMinimumSize(QtCore.QSize(0, 110))
        self.Reaccion.setMaximumSize(QtCore.QSize(450, 110))
        self.Reaccion.setObjectName(_fromUtf8("Reaccion"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Reaccion)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lb_cao_12 = QtGui.QLabel(self.Reaccion)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lb_cao_12.setFont(font)
        self.lb_cao_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cao_12.setObjectName(_fromUtf8("lb_cao_12"))
        self.verticalLayout_4.addWidget(self.lb_cao_12)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lb_cao_13 = QtGui.QLabel(self.Reaccion)
        self.lb_cao_13.setObjectName(_fromUtf8("lb_cao_13"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lb_cao_13)
        self.le_molA = QtGui.QLineEdit(self.Reaccion)
        self.le_molA.setMinimumSize(QtCore.QSize(50, 0))
        self.le_molA.setObjectName(_fromUtf8("le_molA"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_molA)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lb_cao_14 = QtGui.QLabel(self.Reaccion)
        self.lb_cao_14.setObjectName(_fromUtf8("lb_cao_14"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lb_cao_14)
        self.le_molB = QtGui.QLineEdit(self.Reaccion)
        self.le_molB.setMinimumSize(QtCore.QSize(50, 0))
        self.le_molB.setObjectName(_fromUtf8("le_molB"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_molB)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.Izquierda.addWidget(self.Reaccion)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.Izquierda.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(450, 50))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.rb_exo = QtGui.QRadioButton(self.groupBox)
        self.rb_exo.setObjectName(_fromUtf8("rb_exo"))
        self.horizontalLayout_20.addWidget(self.rb_exo)
        self.rb_endo = QtGui.QRadioButton(self.groupBox)
        self.rb_endo.setObjectName(_fromUtf8("rb_endo"))
        self.horizontalLayout_20.addWidget(self.rb_endo)
        self.Izquierda.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.Izquierda.addItem(spacerItem2)
        self.Parmetros_entrada = QtGui.QGroupBox(Form)
        self.Parmetros_entrada.setMaximumSize(QtCore.QSize(450, 16777215))
        self.Parmetros_entrada.setObjectName(_fromUtf8("Parmetros_entrada"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Parmetros_entrada)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.Parmetros_entrada)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 560))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lb_cao_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_6.setObjectName(_fromUtf8("lb_cao_6"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.lb_cao_6)
        self.cb_orden = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cb_orden.setMinimumSize(QtCore.QSize(146, 27))
        self.cb_orden.setObjectName(_fromUtf8("cb_orden"))
        self.cb_orden.addItem(_fromUtf8(""))
        self.cb_orden.addItem(_fromUtf8(""))
        self.cb_orden.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_orden)
        self.lb_cao_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_9.setObjectName(_fromUtf8("lb_cao_9"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.lb_cao_9)
        self.lb_cao_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_5.setObjectName(_fromUtf8("lb_cao_5"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.lb_cao_5)
        self.lb_cao_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_4.setObjectName(_fromUtf8("lb_cao_4"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.lb_cao_4)
        self.lb_cao_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_7.setObjectName(_fromUtf8("lb_cao_7"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.lb_cao_7)
        self.lb_cao_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_8.setObjectName(_fromUtf8("lb_cao_8"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.LabelRole, self.lb_cao_8)
        self.lb_cao_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_11.setObjectName(_fromUtf8("lb_cao_11"))
        self.formLayout_5.setWidget(13, QtGui.QFormLayout.LabelRole, self.lb_cao_11)
        self.le_temp_ini = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_temp_ini.setMinimumSize(QtCore.QSize(146, 27))
        self.le_temp_ini.setObjectName(_fromUtf8("le_temp_ini"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_temp_ini)
        self.le_concentracion_ini = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_concentracion_ini.setMinimumSize(QtCore.QSize(146, 27))
        self.le_concentracion_ini.setObjectName(_fromUtf8("le_concentracion_ini"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_concentracion_ini)
        self.le_ener_act = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_ener_act.setMinimumSize(QtCore.QSize(146, 27))
        self.le_ener_act.setObjectName(_fromUtf8("le_ener_act"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_ener_act)
        self.le_k = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_k.setMinimumSize(QtCore.QSize(146, 27))
        self.le_k.setObjectName(_fromUtf8("le_k"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.le_k)
        self.le_caudal = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_caudal.setMinimumSize(QtCore.QSize(146, 27))
        self.le_caudal.setObjectName(_fromUtf8("le_caudal"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.FieldRole, self.le_caudal)
        self.le_ah = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_ah.setMinimumSize(QtCore.QSize(146, 27))
        self.le_ah.setObjectName(_fromUtf8("le_ah"))
        self.formLayout_5.setWidget(13, QtGui.QFormLayout.FieldRole, self.le_ah)
        self.lb_cao_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_16.setObjectName(_fromUtf8("lb_cao_16"))
        self.formLayout_5.setWidget(14, QtGui.QFormLayout.LabelRole, self.lb_cao_16)
        self.le_cp = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_cp.setMinimumSize(QtCore.QSize(146, 27))
        self.le_cp.setObjectName(_fromUtf8("le_cp"))
        self.formLayout_5.setWidget(14, QtGui.QFormLayout.FieldRole, self.le_cp)
        self.lb_cao_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_3.setObjectName(_fromUtf8("lb_cao_3"))
        self.formLayout_5.setWidget(16, QtGui.QFormLayout.LabelRole, self.lb_cao_3)
        self.lb_cao = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao.setObjectName(_fromUtf8("lb_cao"))
        self.formLayout_5.setWidget(17, QtGui.QFormLayout.LabelRole, self.lb_cao)
        self.le_conv_ini = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_conv_ini.setMinimumSize(QtCore.QSize(146, 27))
        self.le_conv_ini.setObjectName(_fromUtf8("le_conv_ini"))
        self.formLayout_5.setWidget(16, QtGui.QFormLayout.FieldRole, self.le_conv_ini)
        self.le_conv_fin = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_conv_fin.setMinimumSize(QtCore.QSize(146, 27))
        self.le_conv_fin.setObjectName(_fromUtf8("le_conv_fin"))
        self.formLayout_5.setWidget(17, QtGui.QFormLayout.FieldRole, self.le_conv_fin)
        spacerItem3 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_5.setItem(15, QtGui.QFormLayout.LabelRole, spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_5.setItem(7, QtGui.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_5.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem5)
        spacerItem6 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.formLayout_5.setItem(12, QtGui.QFormLayout.LabelRole, spacerItem6)
        self.lb_cao_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_19.setObjectName(_fromUtf8("lb_cao_19"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.LabelRole, self.lb_cao_19)
        self.lb_cao_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_20.setObjectName(_fromUtf8("lb_cao_20"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.LabelRole, self.lb_cao_20)
        self.lb_cao_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_21.setObjectName(_fromUtf8("lb_cao_21"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.LabelRole, self.lb_cao_21)
        self.lb_cao_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lb_cao_22.setObjectName(_fromUtf8("lb_cao_22"))
        self.formLayout_5.setWidget(11, QtGui.QFormLayout.LabelRole, self.lb_cao_22)
        self.le_diametro = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_diametro.setMinimumSize(QtCore.QSize(146, 27))
        self.le_diametro.setObjectName(_fromUtf8("le_diametro"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.FieldRole, self.le_diametro)
        self.le_longitud = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_longitud.setMinimumSize(QtCore.QSize(146, 27))
        self.le_longitud.setObjectName(_fromUtf8("le_longitud"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.FieldRole, self.le_longitud)
        self.le_coef_U = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_coef_U.setMinimumSize(QtCore.QSize(146, 27))
        self.le_coef_U.setObjectName(_fromUtf8("le_coef_U"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.FieldRole, self.le_coef_U)
        self.le_temp_inter = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.le_temp_inter.setMinimumSize(QtCore.QSize(146, 27))
        self.le_temp_inter.setObjectName(_fromUtf8("le_temp_inter"))
        self.formLayout_5.setWidget(11, QtGui.QFormLayout.FieldRole, self.le_temp_inter)
        self.horizontalLayout_2.addLayout(self.formLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn_reset = QtGui.QPushButton(self.Parmetros_entrada)
        self.btn_reset.setObjectName(_fromUtf8("btn_reset"))
        self.verticalLayout.addWidget(self.btn_reset)
        self.Izquierda.addWidget(self.Parmetros_entrada)
        self._2.addLayout(self.Izquierda)
        spacerItem7 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem7)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plotX = PlotWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotX.sizePolicy().hasHeightForWidth())
        self.plotX.setSizePolicy(sizePolicy)
        self.plotX.setMinimumSize(QtCore.QSize(500, 150))
        self.plotX.setObjectName(_fromUtf8("plotX"))
        self.verticalLayout_2.addWidget(self.plotX)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.lb_cao_17 = QtGui.QLabel(Form)
        self.lb_cao_17.setObjectName(_fromUtf8("lb_cao_17"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.lb_cao_17)
        self.le_xa = QtGui.QLineEdit(Form)
        self.le_xa.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_xa.setReadOnly(True)
        self.le_xa.setObjectName(_fromUtf8("le_xa"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_xa)
        self.horizontalLayout_23.addLayout(self.formLayout_6)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.lb_cao_18 = QtGui.QLabel(Form)
        self.lb_cao_18.setObjectName(_fromUtf8("lb_cao_18"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.lb_cao_18)
        self.le_long1 = QtGui.QLineEdit(Form)
        self.le_long1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_long1.setReadOnly(True)
        self.le_long1.setObjectName(_fromUtf8("le_long1"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_long1)
        self.horizontalLayout_23.addLayout(self.formLayout_7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        spacerItem9 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.plotT = PlotWidget(Form)
        self.plotT.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotT.sizePolicy().hasHeightForWidth())
        self.plotT.setSizePolicy(sizePolicy)
        self.plotT.setMinimumSize(QtCore.QSize(500, 150))
        self.plotT.setObjectName(_fromUtf8("plotT"))
        self.horizontalLayout_22.addWidget(self.plotT)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.lb_cao_10 = QtGui.QLabel(Form)
        self.lb_cao_10.setObjectName(_fromUtf8("lb_cao_10"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.lb_cao_10)
        self.le_temperatura = QtGui.QLineEdit(Form)
        self.le_temperatura.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_temperatura.setReadOnly(True)
        self.le_temperatura.setObjectName(_fromUtf8("le_temperatura"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_temperatura)
        self.horizontalLayout_25.addLayout(self.formLayout_8)
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.le_long2 = QtGui.QLineEdit(Form)
        self.le_long2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_long2.setReadOnly(True)
        self.le_long2.setObjectName(_fromUtf8("le_long2"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_long2)
        self.lb_cao_2 = QtGui.QLabel(Form)
        self.lb_cao_2.setObjectName(_fromUtf8("lb_cao_2"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.lb_cao_2)
        self.horizontalLayout_25.addLayout(self.formLayout_9)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        spacerItem11 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem11)
        self.btn_mostrar_resultados = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mostrar_resultados.sizePolicy().hasHeightForWidth())
        self.btn_mostrar_resultados.setSizePolicy(sizePolicy)
        self.btn_mostrar_resultados.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_mostrar_resultados.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_mostrar_resultados.setFont(font)
        self.btn_mostrar_resultados.setObjectName(_fromUtf8("btn_mostrar_resultados"))
        self.verticalLayout_5.addWidget(self.btn_mostrar_resultados)
        spacerItem12 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem13 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.btn_ejecutar = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ejecutar.sizePolicy().hasHeightForWidth())
        self.btn_ejecutar.setSizePolicy(sizePolicy)
        self.btn_ejecutar.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_ejecutar.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ejecutar.setFont(font)
        self.btn_ejecutar.setObjectName(_fromUtf8("btn_ejecutar"))
        self.horizontalLayout_17.addWidget(self.btn_ejecutar)
        spacerItem14 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        spacerItem15 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(0, 20, -1, -1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.btn_cerrar = QtGui.QPushButton(Form)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_cerrar.setObjectName(_fromUtf8("btn_cerrar"))
        self.horizontalLayout_21.addWidget(self.btn_cerrar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self._2.addLayout(self.verticalLayout_5)
        spacerItem17 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem17)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Reactor FP No Adiabático y No Isotermo", None))
        self.Reaccion.setTitle(_translate("Form", "Reacción", None))
        self.lb_cao_12.setText(_translate("Form", "aA ---> bR", None))
        self.lb_cao_13.setText(_translate("Form", "a [mol]", None))
        self.lb_cao_14.setText(_translate("Form", "b [mol]", None))
        self.groupBox.setTitle(_translate("Form", "Tipo de reacción", None))
        self.rb_exo.setText(_translate("Form", "Exotérmica", None))
        self.rb_endo.setText(_translate("Form", "Endotérmica", None))
        self.Parmetros_entrada.setTitle(_translate("Form", "Parámetros de entrada", None))
        self.lb_cao_6.setText(_translate("Form", "Orden de reacción", None))
        self.cb_orden.setItemText(0, _translate("Form", "0", None))
        self.cb_orden.setItemText(1, _translate("Form", "1", None))
        self.cb_orden.setItemText(2, _translate("Form", "2", None))
        self.lb_cao_9.setText(_translate("Form", "Temperatura inicial [K]", None))
        self.lb_cao_5.setText(_translate("Form", "Concentración inicial [mol/L]", None))
        self.lb_cao_4.setText(_translate("Form", "Energía de activación [J/mol]", None))
        self.lb_cao_7.setText(_translate("Form", "Constante ko", None))
        self.lb_cao_8.setText(_translate("Form", "Caudal [L/s]", None))
        self.lb_cao_11.setText(_translate("Form", "Calor latente [J/mol]", None))
        self.lb_cao_16.setText(_translate("Form", "Calor específico [J/mol·K]", None))
        self.lb_cao_3.setText(_translate("Form", "Conversión inicial", None))
        self.lb_cao.setText(_translate("Form", "Conversión final", None))
        self.lb_cao_19.setText(_translate("Form", "Diámetro tubería [m]", None))
        self.lb_cao_20.setText(_translate("Form", "Longitud tubería [m]", None))
        self.lb_cao_21.setText(_translate("Form", "Coef. transmisión calor [J/m2·s·K]", None))
        self.lb_cao_22.setText(_translate("Form", "Temperatura intercambiador [K]", None))
        self.btn_reset.setText(_translate("Form", "Resetear parámetros", None))
        self.lb_cao_17.setText(_translate("Form", "Conversión", None))
        self.lb_cao_18.setText(_translate("Form", "Longitud [m]", None))
        self.lb_cao_10.setText(_translate("Form", "Temperatura [K]", None))
        self.lb_cao_2.setText(_translate("Form", "Longitud [m]", None))
        self.btn_mostrar_resultados.setText(_translate("Form", "Mostrar Resultados", None))
        self.btn_ejecutar.setText(_translate("Form", "CALCULAR", None))
        self.btn_cerrar.setText(_translate("Form", "Volver al menú principal", None))

from pyqtgraph import PlotWidget
