# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_seleccion.ui'
#
# Created: Sat Jan  7 22:32:50 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ventana_seleccion(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(511, 381)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 211, 311))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 209, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_dis_iso = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_dis_iso.setObjectName("btn_dis_iso")
        self.verticalLayout.addWidget(self.btn_dis_iso)
        self.btn_dis_adi = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_dis_adi.setObjectName("btn_dis_adi")
        self.verticalLayout.addWidget(self.btn_dis_adi)
        self.btn_dis_no_iso_no_adi = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_dis_no_iso_no_adi.setObjectName("btn_dis_no_iso_no_adi")
        self.verticalLayout.addWidget(self.btn_dis_no_iso_no_adi)
        self.btn_dis_con = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_dis_con.setObjectName("btn_dis_con")
        self.verticalLayout.addWidget(self.btn_dis_con)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 20, 211, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 209, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_con_iso = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btn_con_iso.setObjectName("btn_con_iso")
        self.verticalLayout_2.addWidget(self.btn_con_iso)
        self.btn_con_adi = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btn_con_adi.setObjectName("btn_con_adi")
        self.verticalLayout_2.addWidget(self.btn_con_adi)
        self.btn_con_no_iso_no_adi = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btn_con_no_iso_no_adi.setObjectName("btn_con_no_iso_no_adi")
        self.verticalLayout_2.addWidget(self.btn_con_no_iso_no_adi)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 200, 211, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 211, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_fijo_vol = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btn_fijo_vol.setObjectName("btn_fijo_vol")
        self.verticalLayout_3.addWidget(self.btn_fijo_vol)
        self.btn_fijo_conv = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btn_fijo_conv.setObjectName("btn_fijo_conv")
        self.verticalLayout_3.addWidget(self.btn_fijo_conv)
        self.btn_salir = QtGui.QCommandLinkButton(Form)
        self.btn_salir.setGeometry(QtCore.QRect(90, 330, 71, 31))
        self.btn_salir.setObjectName("btn_salir")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Discontinuo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_iso.setText(QtGui.QApplication.translate("Form", "Isotermo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_adi.setText(QtGui.QApplication.translate("Form", "Adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_no_iso_no_adi.setText(QtGui.QApplication.translate("Form", "No isotermo/ No adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_con.setText(QtGui.QApplication.translate("Form", "Condiciones óptimas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Continuo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_con_iso.setText(QtGui.QApplication.translate("Form", "Isotermo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_con_adi.setText(QtGui.QApplication.translate("Form", "Adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_con_no_iso_no_adi.setText(QtGui.QApplication.translate("Form", "No isotermo/ No adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Lecho Fijo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fijo_vol.setText(QtGui.QApplication.translate("Form", "Cálculo del volumen", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fijo_conv.setText(QtGui.QApplication.translate("Form", "Cálculo de la conversión", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_salir.setText(QtGui.QApplication.translate("Form", "Salir", None, QtGui.QApplication.UnicodeUTF8))

