# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reac_isotermo.ui'
#
# Created: Sat Nov 26 12:42:52 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(777, 506)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 331, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_cao_6 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_6.setObjectName("lb_cao_6")
        self.horizontalLayout_7.addWidget(self.lb_cao_6)
        self.cb_orden = QtGui.QComboBox(self.groupBox_2)
        self.cb_orden.setObjectName("cb_orden")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.horizontalLayout_7.addWidget(self.cb_orden)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lb_cao_9 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_9.setObjectName("lb_cao_9")
        self.horizontalLayout_10.addWidget(self.lb_cao_9)
        self.le_temp_ini = QtGui.QLineEdit(self.groupBox_2)
        self.le_temp_ini.setObjectName("le_temp_ini")
        self.horizontalLayout_10.addWidget(self.le_temp_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_cao_5 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_5.setObjectName("lb_cao_5")
        self.horizontalLayout_6.addWidget(self.lb_cao_5)
        self.le_concentracion_ini = QtGui.QLineEdit(self.groupBox_2)
        self.le_concentracion_ini.setObjectName("le_concentracion_ini")
        self.horizontalLayout_6.addWidget(self.le_concentracion_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_cao_4 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_4.setObjectName("lb_cao_4")
        self.horizontalLayout_5.addWidget(self.lb_cao_4)
        self.le_ener_act = QtGui.QLineEdit(self.groupBox_2)
        self.le_ener_act.setObjectName("le_ener_act")
        self.horizontalLayout_5.addWidget(self.le_ener_act)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lb_cao_7 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_7.setObjectName("lb_cao_7")
        self.horizontalLayout_8.addWidget(self.lb_cao_7)
        self.le_k = QtGui.QLineEdit(self.groupBox_2)
        self.le_k.setObjectName("le_k")
        self.horizontalLayout_8.addWidget(self.le_k)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_cao_3 = QtGui.QLabel(self.groupBox_2)
        self.lb_cao_3.setObjectName("lb_cao_3")
        self.horizontalLayout_4.addWidget(self.lb_cao_3)
        self.le_conv_ini = QtGui.QLineEdit(self.groupBox_2)
        self.le_conv_ini.setObjectName("le_conv_ini")
        self.horizontalLayout_4.addWidget(self.le_conv_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_cao = QtGui.QLabel(self.groupBox_2)
        self.lb_cao.setObjectName("lb_cao")
        self.horizontalLayout_2.addWidget(self.lb_cao)
        self.le_conv_fin = QtGui.QLineEdit(self.groupBox_2)
        self.le_conv_fin.setObjectName("le_conv_fin")
        self.horizontalLayout_2.addWidget(self.le_conv_fin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_calcular = QtGui.QPushButton(self.groupBox_2)
        self.btn_calcular.setObjectName("btn_calcular")
        self.verticalLayout.addWidget(self.btn_calcular)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(350, 90, 421, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot = PlotWidget(self.layoutWidget)
        self.plot.setObjectName("plot")
        self.verticalLayout_2.addWidget(self.plot)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lb_cao_10 = QtGui.QLabel(self.layoutWidget)
        self.lb_cao_10.setObjectName("lb_cao_10")
        self.horizontalLayout_11.addWidget(self.lb_cao_10)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_11.addWidget(self.lineEdit_5)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_cao_2 = QtGui.QLabel(self.layoutWidget)
        self.lb_cao_2.setObjectName("lb_cao_2")
        self.horizontalLayout_3.addWidget(self.lb_cao_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Parámetros", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_6.setText(QtGui.QApplication.translate("Form", "Orden Reacción", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(0, QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(1, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(2, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_9.setText(QtGui.QApplication.translate("Form", "Temperatura inicial [K]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_temp_ini.setText(QtGui.QApplication.translate("Form", "350", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_5.setText(QtGui.QApplication.translate("Form", "Concentración inicial [mol/l]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_concentracion_ini.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_4.setText(QtGui.QApplication.translate("Form", "Energía de activación [J/mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.le_ener_act.setText(QtGui.QApplication.translate("Form", "62357.25", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_7.setText(QtGui.QApplication.translate("Form", "Constante ko", None, QtGui.QApplication.UnicodeUTF8))
        self.le_k.setText(QtGui.QApplication.translate("Form", "4e6", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_3.setText(QtGui.QApplication.translate("Form", "Conversión inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.le_conv_ini.setText(QtGui.QApplication.translate("Form", "0.65", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao.setText(QtGui.QApplication.translate("Form", "Conversión final", None, QtGui.QApplication.UnicodeUTF8))
        self.le_conv_fin.setText(QtGui.QApplication.translate("Form", "0.95", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_calcular.setText(QtGui.QApplication.translate("Form", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_10.setText(QtGui.QApplication.translate("Form", "Xa", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_2.setText(QtGui.QApplication.translate("Form", "Tiempo [min]", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
