# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_FP_isotermo.ui'
#
# Created: Sun Jan  8 22:32:12 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1237, 692)
        self._2 = QtGui.QHBoxLayout(Form)
        self._2.setContentsMargins(-1, 20, -1, 25)
        self._2.setObjectName("_2")
        spacerItem = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.Izquierda = QtGui.QVBoxLayout()
        self.Izquierda.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Izquierda.setContentsMargins(0, -1, -1, -1)
        self.Izquierda.setObjectName("Izquierda")
        self.Reaccion = QtGui.QGroupBox(Form)
        self.Reaccion.setMinimumSize(QtCore.QSize(400, 0))
        self.Reaccion.setMaximumSize(QtCore.QSize(400, 170))
        self.Reaccion.setObjectName("Reaccion")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Reaccion)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lb_cao_12 = QtGui.QLabel(self.Reaccion)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setWeight(75)
        font.setBold(True)
        self.lb_cao_12.setFont(font)
        self.lb_cao_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cao_12.setObjectName("lb_cao_12")
        self.verticalLayout_4.addWidget(self.lb_cao_12)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lb_cao_13 = QtGui.QLabel(self.Reaccion)
        self.lb_cao_13.setObjectName("lb_cao_13")
        self.horizontalLayout_14.addWidget(self.lb_cao_13)
        self.le_molA = QtGui.QLineEdit(self.Reaccion)
        self.le_molA.setMinimumSize(QtCore.QSize(146, 27))
        self.le_molA.setObjectName("le_molA")
        self.horizontalLayout_14.addWidget(self.le_molA)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lb_cao_14 = QtGui.QLabel(self.Reaccion)
        self.lb_cao_14.setObjectName("lb_cao_14")
        self.horizontalLayout_16.addWidget(self.lb_cao_14)
        self.le_molB = QtGui.QLineEdit(self.Reaccion)
        self.le_molB.setMinimumSize(QtCore.QSize(146, 27))
        self.le_molB.setObjectName("le_molB")
        self.horizontalLayout_16.addWidget(self.le_molB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lb_cao_15 = QtGui.QLabel(self.Reaccion)
        self.lb_cao_15.setObjectName("lb_cao_15")
        self.horizontalLayout_15.addWidget(self.lb_cao_15)
        self.le_inerte = QtGui.QLineEdit(self.Reaccion)
        self.le_inerte.setMinimumSize(QtCore.QSize(146, 27))
        self.le_inerte.setObjectName("le_inerte")
        self.horizontalLayout_15.addWidget(self.le_inerte)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.Izquierda.addWidget(self.Reaccion)
        self.Parmetros_entrada = QtGui.QGroupBox(Form)
        self.Parmetros_entrada.setMinimumSize(QtCore.QSize(400, 0))
        self.Parmetros_entrada.setMaximumSize(QtCore.QSize(400, 16777215))
        self.Parmetros_entrada.setObjectName("Parmetros_entrada")
        self.verticalLayout = QtGui.QVBoxLayout(self.Parmetros_entrada)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_cao_6 = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao_6.setObjectName("lb_cao_6")
        self.horizontalLayout_7.addWidget(self.lb_cao_6)
        self.cb_orden = QtGui.QComboBox(self.Parmetros_entrada)
        self.cb_orden.setMinimumSize(QtCore.QSize(146, 27))
        self.cb_orden.setObjectName("cb_orden")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.cb_orden.addItem("")
        self.horizontalLayout_7.addWidget(self.cb_orden)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lb_cao_9 = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao_9.setObjectName("lb_cao_9")
        self.horizontalLayout_10.addWidget(self.lb_cao_9)
        self.le_temp_ini = QtGui.QLineEdit(self.Parmetros_entrada)
        self.le_temp_ini.setMinimumSize(QtCore.QSize(146, 27))
        self.le_temp_ini.setObjectName("le_temp_ini")
        self.horizontalLayout_10.addWidget(self.le_temp_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_cao_5 = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao_5.setObjectName("lb_cao_5")
        self.horizontalLayout_6.addWidget(self.lb_cao_5)
        self.le_concentracion_ini = QtGui.QLineEdit(self.Parmetros_entrada)
        self.le_concentracion_ini.setObjectName("le_concentracion_ini")
        self.horizontalLayout_6.addWidget(self.le_concentracion_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_cao_4 = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao_4.setObjectName("lb_cao_4")
        self.horizontalLayout_5.addWidget(self.lb_cao_4)
        self.le_ener_act = QtGui.QLineEdit(self.Parmetros_entrada)
        self.le_ener_act.setMinimumSize(QtCore.QSize(146, 27))
        self.le_ener_act.setObjectName("le_ener_act")
        self.horizontalLayout_5.addWidget(self.le_ener_act)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lb_cao_7 = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao_7.setObjectName("lb_cao_7")
        self.horizontalLayout_8.addWidget(self.lb_cao_7)
        self.le_k = QtGui.QLineEdit(self.Parmetros_entrada)
        self.le_k.setMinimumSize(QtCore.QSize(146, 27))
        self.le_k.setObjectName("le_k")
        self.horizontalLayout_8.addWidget(self.le_k)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lb_cao_8 = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao_8.setObjectName("lb_cao_8")
        self.horizontalLayout_9.addWidget(self.lb_cao_8)
        self.le_caudal = QtGui.QLineEdit(self.Parmetros_entrada)
        self.le_caudal.setMinimumSize(QtCore.QSize(146, 27))
        self.le_caudal.setObjectName("le_caudal")
        self.horizontalLayout_9.addWidget(self.le_caudal)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_cao_3 = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao_3.setObjectName("lb_cao_3")
        self.horizontalLayout_4.addWidget(self.lb_cao_3)
        self.le_conv_ini = QtGui.QLineEdit(self.Parmetros_entrada)
        self.le_conv_ini.setMinimumSize(QtCore.QSize(146, 27))
        self.le_conv_ini.setObjectName("le_conv_ini")
        self.horizontalLayout_4.addWidget(self.le_conv_ini)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lb_cao = QtGui.QLabel(self.Parmetros_entrada)
        self.lb_cao.setObjectName("lb_cao")
        self.horizontalLayout_13.addWidget(self.lb_cao)
        self.le_conv_fin = QtGui.QLineEdit(self.Parmetros_entrada)
        self.le_conv_fin.setMinimumSize(QtCore.QSize(146, 27))
        self.le_conv_fin.setObjectName("le_conv_fin")
        self.horizontalLayout_13.addWidget(self.le_conv_fin)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.btn_reset = QtGui.QPushButton(self.Parmetros_entrada)
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout.addWidget(self.btn_reset)
        self.Izquierda.addWidget(self.Parmetros_entrada)
        self._2.addLayout(self.Izquierda)
        spacerItem3 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.plot = PlotWidget(Form)
        self.plot.setMinimumSize(QtCore.QSize(685, 0))
        self.plot.setObjectName("plot")
        self.verticalLayout_2.addWidget(self.plot)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.lb_cao_10 = QtGui.QLabel(Form)
        self.lb_cao_10.setObjectName("lb_cao_10")
        self.horizontalLayout_11.addWidget(self.lb_cao_10)
        self.le_xa = QtGui.QLineEdit(Form)
        self.le_xa.setMinimumSize(QtCore.QSize(146, 27))
        self.le_xa.setObjectName("le_xa")
        self.horizontalLayout_11.addWidget(self.le_xa)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.lb_cao_2 = QtGui.QLabel(Form)
        self.lb_cao_2.setObjectName("lb_cao_2")
        self.horizontalLayout_3.addWidget(self.lb_cao_2)
        self.le_volumen = QtGui.QLineEdit(Form)
        self.le_volumen.setMinimumSize(QtCore.QSize(146, 27))
        self.le_volumen.setObjectName("le_volumen")
        self.horizontalLayout_3.addWidget(self.le_volumen)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem10 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.btn_ejecutar = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ejecutar.sizePolicy().hasHeightForWidth())
        self.btn_ejecutar.setSizePolicy(sizePolicy)
        self.btn_ejecutar.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_ejecutar.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.btn_ejecutar.setFont(font)
        self.btn_ejecutar.setObjectName("btn_ejecutar")
        self.horizontalLayout_17.addWidget(self.btn_ejecutar)
        spacerItem11 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        spacerItem12 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(0, 20, -1, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem13)
        self.btn_cerrar = QtGui.QPushButton(Form)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(100, 40))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_21.addWidget(self.btn_cerrar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self._2.addLayout(self.verticalLayout_5)
        spacerItem14 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem14)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Reactor FP Adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.Reaccion.setTitle(QtGui.QApplication.translate("Form", "Reacción", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_12.setText(QtGui.QApplication.translate("Form", "aA ---> bR", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_13.setText(QtGui.QApplication.translate("Form", "a [mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_14.setText(QtGui.QApplication.translate("Form", "b [mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_15.setText(QtGui.QApplication.translate("Form", "Inerte [%]", None, QtGui.QApplication.UnicodeUTF8))
        self.Parmetros_entrada.setTitle(QtGui.QApplication.translate("Form", "Parámetros de entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_6.setText(QtGui.QApplication.translate("Form", "Orden de reacción", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(0, QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(1, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_orden.setItemText(2, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_9.setText(QtGui.QApplication.translate("Form", "Temperatura inicial [K]", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_5.setText(QtGui.QApplication.translate("Form", "Concentración inicial [mol/L]", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_4.setText(QtGui.QApplication.translate("Form", "Energía de activación [J/mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_7.setText(QtGui.QApplication.translate("Form", "Constante ko", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_8.setText(QtGui.QApplication.translate("Form", "Caudal [L/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_3.setText(QtGui.QApplication.translate("Form", "Conversión inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao.setText(QtGui.QApplication.translate("Form", "Conversión final", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset.setText(QtGui.QApplication.translate("Form", "Resetear parámetros", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_10.setText(QtGui.QApplication.translate("Form", "Xa", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cao_2.setText(QtGui.QApplication.translate("Form", "Volumen [L]", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ejecutar.setText(QtGui.QApplication.translate("Form", "CALCULAR", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cerrar.setText(QtGui.QApplication.translate("Form", "VOLVER", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
