# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_seleccion.ui'
#
# Created: Sun Jan 22 13:23:38 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ventana_seleccion(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 425)
        Form.setMinimumSize(QtCore.QSize(570, 425))
        Form.setMaximumSize(QtCore.QSize(570, 425))
        self.verticalLayout_4 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtGui.QSpacerItem(20, 11, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_dis_iso = QtGui.QPushButton(self.groupBox)
        self.btn_dis_iso.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_dis_iso.setObjectName("btn_dis_iso")
        self.verticalLayout_7.addWidget(self.btn_dis_iso)
        self.btn_dis_adi = QtGui.QPushButton(self.groupBox)
        self.btn_dis_adi.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_dis_adi.setObjectName("btn_dis_adi")
        self.verticalLayout_7.addWidget(self.btn_dis_adi)
        self.btn_dis_no_iso_no_adi = QtGui.QPushButton(self.groupBox)
        self.btn_dis_no_iso_no_adi.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_dis_no_iso_no_adi.setObjectName("btn_dis_no_iso_no_adi")
        self.verticalLayout_7.addWidget(self.btn_dis_no_iso_no_adi)
        self.btn_dis_con = QtGui.QPushButton(self.groupBox)
        self.btn_dis_con.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_dis_con.setObjectName("btn_dis_con")
        self.verticalLayout_7.addWidget(self.btn_dis_con)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_con_iso = QtGui.QPushButton(self.groupBox_2)
        self.btn_con_iso.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_con_iso.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_con_iso.setObjectName("btn_con_iso")
        self.verticalLayout.addWidget(self.btn_con_iso)
        self.btn_con_adi = QtGui.QPushButton(self.groupBox_2)
        self.btn_con_adi.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_con_adi.setObjectName("btn_con_adi")
        self.verticalLayout.addWidget(self.btn_con_adi)
        self.btn_con_no_iso_no_adi = QtGui.QPushButton(self.groupBox_2)
        self.btn_con_no_iso_no_adi.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_con_no_iso_no_adi.setObjectName("btn_con_no_iso_no_adi")
        self.verticalLayout.addWidget(self.btn_con_no_iso_no_adi)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_fijo_vol = QtGui.QPushButton(self.groupBox_3)
        self.btn_fijo_vol.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_fijo_vol.setObjectName("btn_fijo_vol")
        self.verticalLayout_2.addWidget(self.btn_fijo_vol)
        self.btn_fijo_conv = QtGui.QPushButton(self.groupBox_3)
        self.btn_fijo_conv.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_fijo_conv.setObjectName("btn_fijo_conv")
        self.verticalLayout_2.addWidget(self.btn_fijo_conv)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.btn_salir = QtGui.QCommandLinkButton(Form)
        self.btn_salir.setMaximumSize(QtCore.QSize(80, 30))
        self.btn_salir.setObjectName("btn_salir")
        self.verticalLayout_4.addWidget(self.btn_salir)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Reactores", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Reactor Discontinuo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_iso.setText(QtGui.QApplication.translate("Form", "Isotermo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_adi.setText(QtGui.QApplication.translate("Form", "Adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_no_iso_no_adi.setText(QtGui.QApplication.translate("Form", "No isotermo/ No adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dis_con.setText(QtGui.QApplication.translate("Form", "Condiciones óptimas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Reactor Flujo Pistón", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_con_iso.setText(QtGui.QApplication.translate("Form", "Isotermo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_con_adi.setText(QtGui.QApplication.translate("Form", "Adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_con_no_iso_no_adi.setText(QtGui.QApplication.translate("Form", "No isotermo/ No adiabático", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Reactor Mezcla Perfecta", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fijo_vol.setText(QtGui.QApplication.translate("Form", "Cálculo del volumen", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fijo_conv.setText(QtGui.QApplication.translate("Form", "Cálculo de la conversión", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_salir.setText(QtGui.QApplication.translate("Form", "Salir", None, QtGui.QApplication.UnicodeUTF8))

